/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileSnapshotIdRouteImport } from './routes/profile.$snapshotId'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiParseRouteImport } from './routes/api/parse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSnapshotIdRoute = ProfileSnapshotIdRouteImport.update({
  id: '/profile/$snapshotId',
  path: '/profile/$snapshotId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseRoute = ApiParseRouteImport.update({
  id: '/api/parse',
  path: '/api/parse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/parse': typeof ApiParseRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/upload': typeof ApiUploadRoute
  '/profile/$snapshotId': typeof ProfileSnapshotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/parse': typeof ApiParseRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/upload': typeof ApiUploadRoute
  '/profile/$snapshotId': typeof ProfileSnapshotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/parse': typeof ApiParseRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/upload': typeof ApiUploadRoute
  '/profile/$snapshotId': typeof ProfileSnapshotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/parse' | '/api/profile' | '/api/upload' | '/profile/$snapshotId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/api/parse' | '/api/profile' | '/api/upload' | '/profile/$snapshotId'
  id:
    | '__root__'
    | '/'
    | '/api/parse'
    | '/api/profile'
    | '/api/upload'
    | '/profile/$snapshotId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiParseRoute: typeof ApiParseRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ProfileSnapshotIdRoute: typeof ProfileSnapshotIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$snapshotId': {
      id: '/profile/$snapshotId'
      path: '/profile/$snapshotId'
      fullPath: '/profile/$snapshotId'
      preLoaderRoute: typeof ProfileSnapshotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse': {
      id: '/api/parse'
      path: '/api/parse'
      fullPath: '/api/parse'
      preLoaderRoute: typeof ApiParseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiParseRoute: ApiParseRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiUploadRoute: ApiUploadRoute,
  ProfileSnapshotIdRoute: ProfileSnapshotIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
