/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiFetchProfileRouteImport } from './routes/api/fetch-profile'
import { Route as ApiParseRouteImport } from './routes/api/parse'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ResultsAnalysisIdRouteImport } from './routes/results.$analysisId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchProfileRoute = ApiFetchProfileRouteImport.update({
  id: '/api/fetch-profile',
  path: '/api/fetch-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseRoute = ApiParseRouteImport.update({
  id: '/api/parse',
  path: '/api/parse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsAnalysisIdRoute = ResultsAnalysisIdRouteImport.update({
  id: '/results/$analysisId',
  path: '/results/$analysisId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/fetch-profile': typeof ApiFetchProfileRoute
  '/api/parse': typeof ApiParseRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/upload': typeof ApiUploadRoute
  '/results/$analysisId': typeof ResultsAnalysisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/fetch-profile': typeof ApiFetchProfileRoute
  '/api/parse': typeof ApiParseRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/upload': typeof ApiUploadRoute
  '/results/$analysisId': typeof ResultsAnalysisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/fetch-profile': typeof ApiFetchProfileRoute
  '/api/parse': typeof ApiParseRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/upload': typeof ApiUploadRoute
  '/results/$analysisId': typeof ResultsAnalysisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/analyze'
    | '/api/fetch-profile'
    | '/api/parse'
    | '/api/profile'
    | '/api/upload'
    | '/results/$analysisId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/analyze'
    | '/api/fetch-profile'
    | '/api/parse'
    | '/api/profile'
    | '/api/upload'
    | '/results/$analysisId'
  id:
    | '__root__'
    | '/'
    | '/api/analyze'
    | '/api/fetch-profile'
    | '/api/parse'
    | '/api/profile'
    | '/api/upload'
    | '/results/$analysisId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiFetchProfileRoute: typeof ApiFetchProfileRoute
  ApiParseRoute: typeof ApiParseRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ResultsAnalysisIdRoute: typeof ResultsAnalysisIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-profile': {
      id: '/api/fetch-profile'
      path: '/api/fetch-profile'
      fullPath: '/api/fetch-profile'
      preLoaderRoute: typeof ApiFetchProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse': {
      id: '/api/parse'
      path: '/api/parse'
      fullPath: '/api/parse'
      preLoaderRoute: typeof ApiParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$analysisId': {
      id: '/results/$analysisId'
      path: '/results/$analysisId'
      fullPath: '/results/$analysisId'
      preLoaderRoute: typeof ResultsAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiFetchProfileRoute: ApiFetchProfileRoute,
  ApiParseRoute: ApiParseRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiUploadRoute: ApiUploadRoute,
  ResultsAnalysisIdRoute: ResultsAnalysisIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
